apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: hands-on-nginx
  name: hands-on-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on-nginx
  template:
    spec:
    metadata:
      labels:
        app: hands-on-nginx
    spec:
      containers:
      - image: test/hands-on:hands-on-nginx # タグ名を自身のImageのものに変更
        name: hands-on-nginx
        ports:
        - containerPort: 80